name: bindx
description: A powerful, annotation-based state management library for Flutter with reactive programming and advanced async features.
version: 0.0.1
homepage: https://github.com/Avijitbera/bindx
repository: https://github.com/Avijitbera/bindx
issue_tracker: https://github.com/Avijitbera/bindx/issues
documentation: https://github.com/Avijitbera/bindx#readme

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^8.4.1
  build: ^3.0.0
  collection: ^1.18.0
  crypto: ^3.0.7
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  source_gen: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
